name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:  
      - master
      - pipeline

stages:
- stage: build
  jobs:
  - job:
    pool:
      vmImage: windows-latest
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: build
        arguments: '-c Release'
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: $(Pipeline.Workspace)/bin/release/netcoreapp2.2/*
        archiveType: zip
        archiveFile: $(Pipeline.Workspace)/function.zip
    - publish: $(Pipeline.Workspace)/function.zip
      artifact: app 
- stage: deploy
  jobs:
  - deployment:
    environment: dev
    pool:
      vmImage: windows-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'mjgfndev publish profile'
              WebAppKind: 'functionApp'
              WebAppName: 'mjgfndev'
              packageForLinux: '**/*.zip'
              enableCustomDeployment: true
              DeploymentType: 'runFromZip'  
